### ISSUE TITLE
sidenav is not building full API for full scope of component 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-sidenav#15]
### Please verify the version of auro-sidenav you have installed

@latest

### Please describe the bug

In reviewing the page in the Auro doc site, I noticed that the API page only references the API from the sidenav element itself, not the sidenavitem element too. 

This is clear from this line in the package.json 

```
    "build:api": "wca analyze 'src/auro-sidenav.js' --outFiles docs/api.md",
```

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

The dynamic API documentation should be exported for the full scope of the element. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Additional context

none

### Exit criteria

This issue can be closed once the API docs are filly exported and all examples are illustrated in the API pages for this component.

**Comment by Patrick-Daly-AA** [comment]
Reference other multi-element components like Auro Radio for examples

**Comment by jordanjones243** [comment]
This issue was fixed by the work done in this PR:
- https://github.com/AlaskaAirlines/auro-sidenav/pull/20
