### ISSUE TITLE
Icons are not centered for each sidenav option

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-sidenav#17]
### Please verify the version of auro-sidenav you have installed

1.1.6

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/sidenav
2. See default example
3. See icons not centered vertically

### Reproducing the error

None

### Expected behavior

All icons are vertically centered within their respective parent elements

### What browsers are you seeing the problem on?

Chrome

### Exit criteria

All icons are centered

**Comment by Patrick-Daly-AA** [comment]
This could be an issue where the shape of the svg is getting elongated in the HTML and thus isn't being centered properly when embedded
