### ISSUE TITLE
Releases tab for Auro-sidenav points to Auro-alert

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-sidenav#22]
### Please describe the bug

1. Go to the doc site.
1. Click on the auro-sidenav
1. Click on the releases tab and see the auro-alert releases.

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

It should show the auro-sidenav releases.

### Additional context

The issue shows up on the doc site so it may need to be updated there instead of in the component.

### Exit criteria

The doc site shows the releases for auro-sidenav

**Comment by jason-capsule42** [comment]
This is being handled in this ticket and a fix is already up for review: https://github.com/AlaskaAirlines/AuroDocsSite/issues/202
