### ISSUE TITLE
auro-sidenav: update usage of Accordion to support new Accordion API

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/auro-sidenav#5]
### Is your feature request related to a problem? Please describe.

When the next release of Auro-Accordion goes out, the API is changing.  SideNav needs to be updated to use the new API

### Additional context

This work is dependent on the 3.X release of Auro Accordion

**Comment by jordanjones243** [comment]
This issue was fixed by the work in this PR:
- https://github.com/AlaskaAirlines/auro-sidenav/pull/20
